name: clang-format
on: [pull_request]
jobs:
  format-files:
    name: Clang format
    runs-on: [self-hosted, Linux]
    steps:
    - uses: actions/checkout@v2
    - name: Run clang-format for C/C++ source files.
      uses: AmyrAhmady/clang-format-action@v1.4
      with:
        clang-format-version: '11'
        sources: "Server/**/*.hpp,SDK/**/*.hpp,Server/**/*.cpp,SDK/**/*.cpp"
        fallback-style: 'WebKit'
    - name: Commit and push
      run: |
        git config --global user.name 'auto-format'
        git config --global user.email 'auto-format@auto.format'
        git add ./Server
        git add ./SDK
        git commit -am "clang-format: ato format after push"
        git push
