name: clang-format
on: [pull_request]
jobs:
  format-files:
    name: Clang format
    runs-on: [self-hosted, Linux]
    steps:
      - uses: actions/checkout@v2
      - name: Run clang-format for C/C++ source files.
        uses: AmyrAhmady/clang-format-action@v1.5
        with:
          clang-format-version: "11"
          sources: "Server/**/*.hpp,SDK/**/*.hpp,Server/**/*.cpp,SDK/**/*.cpp"
          fallback-style: "WebKit"
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "clang-format: format files"
          commit_user_name: clnag-format # defaults to "GitHub Actions"
          commit_user_email: clang-format@open.mp # defaults to "actions@github.com"
          commit_author: clang-format <clang-format@open.mp> # defaults to author of the commit that triggered the run
