name: Update SDK & Network
on:
  workflow_dispatch:
  push:
    branches:
      - "stable"
jobs:
  update-sdk:
    runs-on: ubuntu-latest

    steps:
      - name: Clone SDK repository
        uses: actions/checkout@v3
        with:
          clean: true
          repository: "openmultiplayer/open.mp-sdk"
          path: "SDK"
          ref: "master"
          submodules: recursive
          token: ${{ secrets.CI_TOKEN }}

      - name: Update SDK files from dev branch
        if: always()
        shell: bash
        run: |
          cd SDK
          git fetch
          git rebase origin/dev
          git push || true

  update-network:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Network repository
        uses: actions/checkout@v3
        with:
          clean: true
          repository: "openmultiplayer/open.mp-network"
          path: "Network"
          ref: "master"
          submodules: recursive
          token: ${{ secrets.CI_TOKEN }}

      - name: Update Network files from dev branch
        if: always()
        shell: bash
        run: |
          cd Network
          git fetch
          git rebase origin/dev
          git push || true
